name: CHAPMAN
root: /data/padmalab_external/special_project/chapman_shaoxing
metadata_file: Diagnostics.xlsx
records_root: ECGData
sampling_rate: 500
target_sampling_rate: 500
target_length: 5000
normalization: per_lead_zscore
lead_order: [I, II, III, aVR, aVL, aVF, V1, V2, V3, V4, V5, V6]
signal_format: csv
record_id_column: FileName
label_column: Rhythm
beat_label_column: Beat
domain: chapman_ningbo_china
